
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 01 11:58:32 AST 2020
//----------------------------------------------------

package analizer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int No_Igual = 9;
  public static final int If = 2;
  public static final int Menor = 7;
  public static final int ERROR = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Mayor = 5;
  public static final int Igual = 10;
  public static final int Menor_Igual = 8;
  public static final int Numero = 12;
  public static final int Cierra_Parentesis = 4;
  public static final int Abre_Parentesis = 3;
  public static final int Mayor_Igual = 6;
}

